version: '3.3'

services:
   db:
      image: postgres:13
      ports:
         - 5432:5432
      environment:
         POSTGRES_PASSWORD: sqljoke

   adminer:
      image: adminer
      ports:
         - 8888:8080