"""
Prepare global constants
"""
INITIAL_FREQ = 10**7
INTERVAL_CALIB = 10**5
INTERVAL_HALF = 10**4 // 1
INTERVAL_STEP = 40
POLYFIT_COEFFICIENT = 0.95
DISSIPATION_PERCENT = 0.707
CSV_SEPARATOR = ','
DATE_SEPARATOR = '_'
RAW_DATA_SEPARATOR = ';'
OUTPUT_EXT = 'output'
RAW_DATA_EXT = 'txt'

STATUS_ERROR = 0
STATUS_IDLE = 1
STATUS_CALIBRATING = 2
STATUS_CALIBRATED = 3
STATUS_MEASURING = 4
